### ISSUE TITLE
кнопку без очереди заменить на сейчас

### ISSUE THREAD

**Issue by SvineruS** [SvineruS/kpi_radio_bot#56]
шоб хуярило прям вне эфира даже

**Comment by mnb3000** [comment]
@SvineruS Ток не забудь после песни вырубать нахуй

**Comment by SvineruS** [comment]
> @SvineruS Ток не забудь после песни вырубать нахуй

каво?

**Comment by mnb3000** [comment]
@SvineruS Если эфир не идёт то вырубать после песни рупора

**Comment by mnb3000** [comment]
@mnb3000 А, бля, это ещё и для 24/7, точно

**Comment by SvineruS** [comment]
я и не хотел врубать по кнопке
